export const OBTER_PROFESSORES = "OBTER_PROFESSORES"
export const CADASTRAR_PROFESSOR = "CADASTRAR_PROFESSOR"
export const ALTERAR_PROFESSOR = "ALTERAR_PROFESSOR"
export const REMOVER_PROFESSOR = "REMOVER_PROFESSOR"

export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA"
export const ALTERAR_TAREFA = "ALTERAR_TAREFA"