export const ADICIONA_PROFESSOR = 'ADICIONA_PROFESSOR'
export const ALTER_PROFESSOR = 'ALTER_PROFESSOR'
export const EXCLUIR_PROFESSOR = 'EXCLUIR_PROFESSOR'
export const DEFINIR_PROFESSORES = 'DEFINIR_PROFESSORES'
export const NOTIFICAR = 'NOTIFICAR'

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const ALTERA_TAREFA = "ALTERA_TAREFA"